name       : qtox
version    : 1.9.0
release    : 16
source     :
    - https://github.com/qTox/qTox/archive/v1.9.0.tar.gz : aceaac0c9cf8c9c98e364c8380f992547f369db6f0ac62505531c0474c7e04d6
license    : GPL-3.0
component  : network.im
summary    : qTox is a powerful Tox client.
description: |
    qTox is a powerful Tox client.
builddeps  :
    - pkgconfig(filteraudio)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libavcodec)
    - pkgconfig(libqrencode)
    - pkgconfig(libsodium)
    - pkgconfig(libtoxcore)
    - pkgconfig(openal)
    - pkgconfig(opencv)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Svg)
    - pkgconfig(sqlcipher)
    - pkgconfig(vpx)
    - pkgconfig(xscrnsaver)
setup      : |
    sed -i -e 's|AudioVideo;||g' qTox.desktop
build      : |
    install -d build
    cd build
    qmake ENABLE_SYSTRAY_UNITY_BACKEND=NO ..
    %make
install    : |
    install -Dm755 build/qtox $installdir/usr/bin/qtox
    install -Dm644 qTox.desktop $installdir/usr/share/applications/qTox.desktop
    cd img/icons
    rm qtox*
    for size in *x*; do
        install -Dm644 "$size/qtox.png" "$installdir/usr/share/icons/hicolor/$size/apps/qtox.png"
    done
