name       : qtox
version    : 1.14.1
release    : 25
source     :
    - https://github.com/qTox/qTox/archive/v1.14.1.tar.gz : baa7b86cf54371e1d0fae4e56d12f15c75b6f43d113057e740ba98772def149d
license    : GPL-3.0-or-later
component  : network.im
summary    : qTox is a powerful Tox client
description: |
    The most feature-rich Tox client; P2P instant messaging, audio and video calls.
builddeps  :
    - pkgconfig(filteraudio)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libavcodec)
    - pkgconfig(libexif)
    - pkgconfig(libqrencode)
    - pkgconfig(libsodium)
    - pkgconfig(toxcore)
    - pkgconfig(openal)
    - pkgconfig(opencv)
    - pkgconfig(opus)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Svg)
    - pkgconfig(sqlcipher)
    - pkgconfig(vpx)
    - pkgconfig(xscrnsaver)
setup      : |
    %cmake -DGIT_DESCRIBE=v$version .
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
