name       : qtox
version    : 1.4.1
release    : 9
source     :
    - https://github.com/tux3/qTox/archive/v1.4.1.tar.gz : 752e5efdde5e0dfb66d9f5cd0660eb989b41bd4fcfcd3a1e607bee8bde496c84
license    : GPL-3.0
component  : network.im
summary    : qTox is a powerful Tox client.
description: |
    qTox is a powerful Tox client.
builddeps  :
    - pkgconfig(filteraudio)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libavcodec)
    - pkgconfig(libqrencode)
    - pkgconfig(libsodium)
    - pkgconfig(libtoxcore)
    - pkgconfig(openal)
    - pkgconfig(opencv)
    - pkgconfig(Qt5Core)
    - pkgconfig(sqlcipher)
    - pkgconfig(vpx)
    - pkgconfig(xscrnsaver)
setup      : |
    sed -i -e 's|AudioVideo;||g' qTox.desktop
build      : |
    install -d build
    cd build
    qmake ENABLE_SYSTRAY_UNITY_BACKEND=NO ..
    %make
install    : |
    install -Dm755 build/qtox $installdir/usr/bin/qtox
    install -Dm644 qTox.desktop $installdir/usr/share/applications/qTox.desktop
    cd img/icons
    rm qtox*
    for size in *x*; do
        install -Dm644 "$size/qtox.png" "$installdir/usr/share/icons/hicolor/$size/apps/qtox.png"
    done
