name       : qtox
version    : 1.2.4
release    : 5
source     :
    - https://github.com/tux3/qTox/archive/v1.2.4.tar.gz : af9b1308865dfbba0ed2a4d6a19e676d59794f850a17da86f9ce2bfbb56adfdd
license    : GPL-3.0
summary    : qTox is a powerful Tox client.
description: |
    qTox is a powerful Tox client.
builddeps  :
    - pkgconfig(filteraudio)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libavcodec)
    - pkgconfig(libqrencode)
    - pkgconfig(libsodium)
    - pkgconfig(libtoxcore)
    - pkgconfig(openal)
    - pkgconfig(opencv)
    - pkgconfig(Qt5Core)
    - pkgconfig(sqlcipher)
    - pkgconfig(vpx)
    - pkgconfig(xscrnsaver)
build      : |
    install -d build
    cd build
    qmake ENABLE_SYSTRAY_UNITY_BACKEND=NO ..
    %make
install    : |
    install -Dm755 build/qtox $installdir/usr/bin/qtox
    install -Dm644 qTox.desktop $installdir/usr/share/applications/qTox.desktop
    cd img/icons
    for _icon in *.png; do
        _size=$(sed 's|^[^-]*-||;s|\.png||' <<< "$_icon")
        install -Dm644 "$_icon" "$installdir/usr/share/icons/hicolor/$_size/apps/qtox.png"
    done
