name       : qtox
version    : 1.11.0
release    : 20
source     :
    - https://github.com/qTox/qTox/archive/v1.11.0.tar.gz : be38517cd915727dbd9b3cd2a51bbaf1cae28290de07a34c759ec8b77c502cd4
license    : GPL-3.0
component  : network.im
summary    : qTox is a powerful Tox client.
description: |
    qTox is a powerful Tox client.
builddeps  :
    - pkgconfig(filteraudio)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libavcodec)
    - pkgconfig(libqrencode)
    - pkgconfig(libsodium)
    - pkgconfig(libtoxcore)
    - pkgconfig(openal)
    - pkgconfig(opencv)
    - pkgconfig(opus)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Svg)
    - pkgconfig(sqlcipher)
    - pkgconfig(vpx)
    - pkgconfig(xscrnsaver)
setup      : |
    sed -i -e 's|AudioVideo;||g' qtox.desktop
    %cmake .
build      : |
    %make
install    : |
    install -Dm755 qtox $installdir/usr/bin/qtox
    install -Dm644 qtox.desktop $installdir/usr/share/applications/qtox.desktop
    cd img/icons
    rm qtox*
    for size in *x*; do
        install -Dm644 "$size/qtox.png" "$installdir/usr/share/icons/hicolor/$size/apps/qtox.png"
    done
