name       : qtox
version    : 1.16.1
release    : 27
source     :
    - https://github.com/qTox/qTox/archive/v1.16.1.tar.gz : 44a60174b0582f9d04c132dd4de663b7d67e2d68fee55912c6449a07389d8486
license    : GPL-3.0-or-later
component  : network.im
summary    : qTox is a powerful Tox client
description: |
    The most feature-rich Tox client; P2P instant messaging, audio and video calls.
builddeps  :
    - pkgconfig(filteraudio)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libavcodec)
    - pkgconfig(libexif)
    - pkgconfig(libqrencode)
    - pkgconfig(libsodium)
    - pkgconfig(toxcore)
    - pkgconfig(openal)
    - pkgconfig(opencv)
    - pkgconfig(opus)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Svg)
    - pkgconfig(sqlcipher)
    - pkgconfig(vpx)
    - pkgconfig(xscrnsaver)
setup      : |
    %cmake -DGIT_DESCRIBE=v$version .
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
