name       : qtox
version    : 1.13.0
release    : 23
source     :
    - https://github.com/qTox/qTox/archive/v1.13.0.tar.gz : 8a85b47f5a1033e997e16616ddeeb9af277b2f8ee3fe06cf5b9f3c8869a5d737
license    : GPL-3.0
component  : network.im
summary    : qTox is a powerful Tox client
description: |
    The most feature-rich Tox client; P2P instant messaging, audio and video calls.
builddeps  :
    - pkgconfig(filteraudio)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libavcodec)
    - pkgconfig(libexif)
    - pkgconfig(libqrencode)
    - pkgconfig(libsodium)
    - pkgconfig(libtoxcore)
    - pkgconfig(openal)
    - pkgconfig(opencv)
    - pkgconfig(opus)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Svg)
    - pkgconfig(sqlcipher)
    - pkgconfig(vpx)
    - pkgconfig(xscrnsaver)
setup      : |
    %patch -p1 < $pkgfiles/0001-backout-werror.patch
    sed -i -e 's|AudioVideo;||g' qtox.desktop
    %cmake .
build      : |
    %make
install    : |
    install -Dm00755 qtox $installdir/usr/bin/qtox
    install -Dm00644 qtox.desktop $installdir/usr/share/applications/qtox.desktop
    cd img/icons
    rm qtox*
    for size in *x*; do
        install -Dm00644 "$size/qtox.png" "$installdir/usr/share/icons/hicolor/$size/apps/qtox.png"
    done
check      : |
    %make test
